{
    "name":"Latihan Addon Management Odoo",
    "version":"1.0",
    "depends":["base","hr",],
    "author":"Ferdiansah",
    "category":"New Module",
    "website":"https://github.com/ferdiansahgg",
    "description":"Ini adalah addons management latihan",
    "data":[
        "menu.xml",
        "assetdc.xml",
        "assetnondc.xml",
        "layout.xml",
        "power.xml",
        "lan.xml",
        "sop.xml",
        "bcp.xml",
        "berita.xml",
        "agenda.xml",
        "maintenance.xml",
        "perangkat.xml",
        "sdm.xml",
        "capacity.xml",
        "userdata.xml",
        "updatemodule.xml",
        "lokasi.xml",
        "ruang.xml",
        "subruang.xml",
        "merk.xml",
        "unit.xml",
        "subunit.xml",
        "kodeperangkat.xml",
        "kelompokperangkat.xml",
        "security/ir.model.access.csv",
    ],
    
}